### ISSUE TITLE
optimizing a parameter that doesn't require gradients

### ISSUE THREAD

**Issue by yuanjinsheng** [krrish94/DeepVO#5]
when i run "python3 -B main.py -datadir ~/scratch/KITTIOdometry/dataset/ -cachedir ../../scratch/DeepVOCache -nepochs 2 -tensorboardX True -lrScheduler cosine -expID tmp -scf 2 -lr 1e-3 -beta1 0.7 -momentum 0.009 -optMethod sgd -dropout 0.5 -modelType flownet -loadModel cache/flownets_EPE1.951.pth.tar -trainBatch 40 -sbatch True -snapshot 1 -snapshotStrategy none -gradClip 20. -imageWidth 640 -imageHeight 192"

 File "main.py", line 140, in <module>
    optimizer = optim.SGD(deepVO.parameters(), lr = cmd.lr, momentum = cmd.momentum, weight_decay = cmd.weightDecay, nesterov = False)
  File "/home/yjs/.local/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/yjs/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 43, in __init__
    self.add_param_group(param_group)
  File "/home/yjs/.local/lib/python3.6/site-packages/torch/optim/optimizer.py", line 193, in add_param_group
    raise ValueError("optimizing a parameter that doesn't require gradients")
ValueError: optimizing a parameter that doesn't require gradients

**Comment by krrish94** [comment]
Try changing `deepVO.parameters()` to `filter(lambda p: p.requires_grad, deepVO.parameters())`
